from googletrans import Translator


countryCodes = {
    "afghanistan": "en",
    "albania": "sq",
    "algeria": "ar",
    "andorra": "ca",
    "angola": "pt",
    "antigua and barbuda": "en",
    "argentina": "es",
    "armenia": "hy",
    "australia": "en",
    "austria": "de",
    "assamese": "as",
    "azerbaijan": "az",
    "bahamas": "en",
    "bahrain": "ar",
    "bangladesh": "bn",
    "barbados": "en",
    "belarus": "be",
    "belgium": "nl",
    "belize": "en",
    "benin": "fr",
    "bengali": "bn",
    "bhutan": "dz",
    "bolivia": "es",
    "bosnia and herzegovina": "bs",
    "botswana": "en",
    "brazil": "pt",
    "brunei": "ms",
    "bulgaria": "bg",
    "burkina faso": "fr",
    "burundi": "fr",
    "cabo verde": "pt",
    "cambodia": "km",
    "cameroon": "fr",
    "canada": "en",
    "central african republic": "fr",
    "chad": "fr",
    "chile": "es",
    "china": "zh-CN",
    "colombia": "es",
    "comoros": "ar",
    "congo": "fr",
    "costa rica": "es",
    "côte d'ivoire": "fr",
    "croatia": "hr",
    "cuba": "es",
    "cyprus": "el",
    "czechia": "cs",
    "denmark": "da",
    "djibouti": "fr",
    "dominica": "en",
    "dominican republic": "es",
    "ecuador": "es",
    "egypt": "ar",
    "el salvador": "es",
    "equatorial guinea": "es",
    "eritrea": "ti",
    "estonia": "et",
    "eswatini": "en",
    "ethiopia": "am",
    "fiji": "en",
    "finland": "fi",
    "france": "fr",
    "gabon": "fr",
    "gambia": "en",
    "georgia": "ka",
    "germany": "de",
    "ghana": "en",
    "greece": "el",
    "grenada": "en",
    "guatemala": "es",
    "guinea": "fr",
    "guinea-bissau": "pt",
    "guyana": "en",
    "gujarati": "gu",
    "haiti": "fr",
    "honduras": "es",
    "hungary": "hu",
    "iceland": "is",
    "india": "en",  # English is included as well
    "telugu": "te",
    "tamil": "ta",
    "hindi": "hi",
    "indonesia": "id",
    "iran": "fa",
    "iraq": "ar",
    "ireland": "en",
    "israel": "he",
    "italy": "it",
    "jamaica": "en",
    "japan": "ja",
    "jordan": "ar",
    "kannada": "kn",
    "kazakhstan": "kk",
    "kenya": "en",
    "kiribati": "en",
    "korea, north": "ko",
    "korea, south": "ko",
    "kosovo": "sq",
    "kuwait": "ar",
    "kyrgyzstan": "ky",
    "laos": "lo",
    "latvia": "lv",
    "lebanon": "ar",
    "lesotho": "en",
    "liberia": "en",
    "libya": "ar",
    "liechtenstein": "de",
    "lithuania": "lt",
    "luxembourg": "lb",
    "madagascar": "mg",
    "maithili": "mai",
    "malawi": "en",
    "marathi": "mr",
    "malaysia": "ms",
    "maldives": "dv",
    "mali": "fr",
    "malta": "mt",
    "malayalam": "ml",
    "marshall islands": "en",
    "mauritania": "ar",
    "mauritius": "en",
    "mexico": "es",
    "micronesia": "en",
    "moldova": "ro",
    "monaco": "fr",
    "mongolia": "mn",
    "montenegro": "sr",
    "morocco": "ar",
    "mozambique": "pt",
    "myanmar": "my",
    "namibia": "en",
    "nauru": "en",
    "nepal": "ne",
    "netherlands": "nl",
    "new zealand": "en",
    "nicaragua": "es",
    "niger": "fr",
    "nigeria": "en",
    "north macedonia": "mk",
    "norway": "no",
    "oman": "ar",
    "odisha": "or",
    "pakistan": "ur",
    "palau": "en",
    "panama": "es",
    "papua new guinea": "en",
    "paraguay": "es",
    "punjabi": "pa",
    "peru": "es",
    "philippines": "en",
    "poland": "pl",
    "portugal": "pt",
    "qatar": "ar",
    "romania": "ro",
    "russia": "ru",
    "rwanda": "rw",
    "saint kitts and nevis": "en",
    "saint lucia": "en",
    "saint vincent and the grenadines": "en",
    "samoa": "en",
    "san marino": "it",
    "sao tome and principe": "pt",
    "saudi arabia": "ar",
    "senegal": "fr",
    "serbia": "sr",
    "seychelles": "fr",
    "sierra leone": "en",
    "singapore": "en",
    "slovakia": "sk",
    "slovenia": "sl",
    "solomon islands": "en",
    "somalia": "so",
    "south africa": "en",
    "south sudan": "en",
    "spain": "es",
    "sri lanka": "si",
    "sudan": "ar",
    "suriname": "nl",
    "sweden": "sv",
    "switzerland": "de",
    "syria": "ar",
    "taiwan": "zh-TW",
    "tajikistan": "tg",
    "tanzania": "sw",
    "thailand": "th",
    "timor-leste": "pt",
    "togo": "fr",
    "tonga": "en",
    "trinidad and tobago": "en",
    "tunisia": "ar",
    "turkey": "tr",
    "turkmenistan": "tk",
    "tuvalu": "en",
    "uganda": "en",
    "ukraine": "uk",
    "united arab emirates": "ar",
    "united kingdom": "en",
    "united states": "en",
    "uruguay": "es",
    "urdu": "ur",
    "uzbekistan": "uz",
    "vanuatu": "bi",
    "vatican city": "la",
    "venezuela": "es",
    "vietnam": "vi",
    "yemen": "ar",
    "zambia": "en",
    "zimbabwe": "en",
    # Add more countries and their respective language codes as needed
}

translator = Translator()

text = input("Enter text to Translate : \n")

Country_name = input('Enter Country Name : \n').lower()

translated_text = translator.translate(text, dest=countryCodes[Country_name], src='auto')

print(translated_text.text)
